# Generated by Django 3.2 on 2023-11-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETE', 'Delete')], default='ACTIVE', max_length=16),
        ),
    ]
